{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf200
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;\red118\green118\blue118;
\red233\green233\blue220;\red204\green195\blue98;\red87\green208\blue234;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;\cssrgb\c100000\c100000\c100000;\cssrgb\c53725\c53725\c53725;
\cssrgb\c92941\c92941\c89020;\cssrgb\c83922\c80000\c45882;\cssrgb\c39608\c84706\c93333;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf2 \cb3 \expnd0\expndtw0\kerning0
# iOS CircleCI 2.0 configuration file\
#\
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details\
#\
\pard\pardeftab720\partightenfactor0
\cf2 version: 2\
jobs:\
  build:\
\
    # Specify the Xcode version to use\
    macos:\
      xcode: "8.3.3"\
\
    steps:\
      - checkout\
\
      # Install CocoaPods\
      - run:\
          name: Install CocoaPods\
          command: pod install\
\
      # Build the app and run tests\
      - run:\
          name: Build and run tests\
          command: fastlane scan\
          environment:\
            SCAN_DEVICE: iPhone 6\
            SCAN_SCHEME: WebTests\
\
      # Collect XML test results data to show in the UI,\
      # and save the same XML files under test-results folder\
      # in the Artifacts tab\
      - store_test_results:\
          path: test_output/report.xml\
      - store_artifacts:\
          path: /tmp/test-results\
          destination: scan-test-results\
      - store_artifacts:\
          path: ~/Library/Logs/scan\
          destination: scan-logs}